# Zoo animal classification

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

import pandas as pd
import numpy as np
import seaborn as sns
import sklearn as sk
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import decomposition
from sklearn.model_selection import train_test_split

#Viendo un poco la información que tenemos...
classes = pd.read_csv('class.csv')


#Viendo un poco más...
zoo = pd.read_csv('zoo.csv')

## Utilizando SVM para reducir dimensiones

In [2]:
#Armo data + target para reducir dimensiones por SVM
_X = zoo.iloc[:,1:17].values   

#valor destino
_y = zoo.iloc[:,17].values

X_train, X_test, y_train, expected = train_test_split(_X, _y, test_size=0.3, random_state=0)


In [5]:
from sklearn import svm
from sklearn import metrics

model = svm.LinearSVC()
model.fit(X_train, y_train)

predicted = model.predict(X_test)
target_names = np.array(classes['Class_Type'])
print(metrics.classification_report(expected, predicted, target_names = target_names))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

      Mammal       1.00      1.00      1.00        11
        Bird       1.00      1.00      1.00         6
     Reptile       1.00      0.50      0.67         2
        Fish       1.00      1.00      1.00         7
   Amphibian       1.00      1.00      1.00         1
         Bug       1.00      1.00      1.00         2
Invertebrate       0.67      1.00      0.80         2

 avg / total       0.98      0.97      0.97        31

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  1  0  0  0  1]
 [ 0  0  0  7  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  2]]


In [6]:
print predicted

[5 4 4 1 1 1 2 4 1 1 7 1 2 7 4 6 1 6 2 4 2 3 1 2 1 1 1 2 4 7 4]


In [7]:
print expected

[5 4 4 1 1 1 2 4 1 1 7 1 2 7 4 6 1 6 2 4 2 3 1 2 1 1 1 2 4 3 4]


# Análisis

Si bien el porcentaje estuvo arriba del 95% de acierto, KNN estuvo mejor. Es necesario tener más datos del grupo 3 - Reptiles para la predicción, es el más problemático. 